 # Author: PAS Group DTU

model_path: weights/yolov8x-seg.onnx
runtime: onnxruntime
providers:
  - CUDAExecutionProvider
  - CPUExecutionProvider
conf_threshold: 0.5
batch_size: 1
conf_thres: 0.7
iou_thres: 0.5
num_masks: 32